---
abstract: 'Generate parse trees for CSS3 selectors.'
author:
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CSS-Selector-Grammar
no_index: {}
requires:
  Exporter: '0'
  Regexp::Grammars: '0'
  parent: '0'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
version: '0.002'
